### ISSUE TITLE
مثالی از ورد تو وک تک

### ISSUE THREAD

**Issue by aminsato** [mhbashari/awesome-persian-nlp-ir#16]
سلام
  قطعه کد پایین یک جمله رو میگیره ورد تو وک تک تک تک کلمات رو برمیگردنه. برای انگلیسی کار میکنه ولی برای فارسی کار نمیکنه .میشه لطف کنید از این کتابخونتون یک مثال مثل این کد بیارید که بشه ورد تو وک تک کلمات جلمه رو برگردونه
```
from gensim.models import Word2Vec as wv
for sentence in sentences:
    tokens = sentence.strip().lower().split(" ")
    tokenized.append(tokens)
model = wv(tokenized
    ,size=5,
          min_count=1)
print('done2')
model.save('F:/text8/text8-phrases1')
print('done3')
print(model)
model = wv.load('F:/text8/text8-phrases1')

print(model.wv.vocab)
```
با تشکر

**Comment by mhbashari** [comment]
سلام
راستش ارتباط سوالتون رو با این ریپاسیتوری نمیفهمم

**Comment by aminsato** [comment]
..ببخشید با دقت ریپوزیتورنو مطالعه نکردم فک کردم وردتوک  توی ریپوزیتوری هستش
حقیقا یه چند هفته برای بخشی از پایان نامه دنبال پیاده سازی وروتووک روی زبان فارسی باشه میگشتم  ولی به تنیحه نرسیدم. 
.آیا شما گروه یا سایتی یا کسی رو میشناسید که به سوالم پاسخ بده
