### ISSUE TITLE
لینک های آزمایشگاه پایگاه داده دانشگاه تهران

### ISSUE THREAD

**Issue by mhbashari** [mhbashari/awesome-persian-nlp-ir#2]
<div dir="rtl">
چند روزی هست که صفحات پیکره های دانشگاه تهران در دسترس نیستند .<br>
لطفا اگر اطلاعی از صفحات مذکور دارید ما رو هم در جریان بگذارید خیلی ممنون
</div>

**Comment by MrHTZ** [comment]
سلام
http://ece.ut.ac.ir/en/node/940

**Comment by mhbashari** [comment]
سلام ممنون لینک داده های بی جن خان، همشهری،وب دات آی آر رو هم اطلاع دارید؟

**Comment by masoodmortazavi** [comment]
All links are broken and unusable. I would have liked to access text corpus for some word embedding exercise.
